### ISSUE TITLE
Can you pls use ini file for username/password in check-postgres-alive.rb[and everywhere else] ?

### ISSUE THREAD

**Issue by Salamek** [sensu-plugins/sensu-plugins-postgres#9]
As is used in mysql implementation https://github.com/sensu-plugins/sensu-plugins-mysql/blob/master/bin/check-mysql-alive.rb

This password and username is everywhere when used as command parameter, logs, etc (yes i use special user for this, but i dont like it anyway)

**Comment by eheydrick** [comment]
postgresql has a pgpass file - I'd take a PR that added support for that. http://www.postgresql.org/docs/9.4/static/libpq-pgpass.html

**Comment by HenryCook** [comment]
I've written something similar to what you've requested, however I'm utilising a YAML file for creds as opposed to an ini file. You can find my gist [here](https://gist.github.com/HenryCook/cbce318a17eca3504d71ecd185673a6c). I've pretty much copied the [check-mysql-alive.rb](https://github.com/sensu-plugins/sensu-plugins-mysql/blob/master/bin/check-mysql-alive.rb) check.

The YAML file will need to look something like this:

```
production:
  host: db_hostname
  port: 1234 (leave this out to default to '5432')
  user: db_user
  password: db_pass
  database: db_name
```

Is that of any use? Would you like a pull request?
